// Building typologies. Each entry carries the dimensional rules the generator
// uses to lay out massing and parking, plus the cost/revenue basis the pro
// forma starts from. Every number here is an editable default, not a constant.

export const PARKING = {
  stallWidth: 9,
  stallDepth: 18,
  aisleWidth: 24,
  // 18 + 24 + 18 -> one double-loaded bay
  get bayDepth() { return this.stallDepth * 2 + this.aisleWidth; },
  gsfPerStructuredStall: 350,
  adaRatio: 0.02,
};

export const UNIT_TYPES = [
  { key: 'studio', name: 'Studio', area: 545, beds: 0, baths: 1, rentPsf: 2.55 },
  { key: 'one', name: '1 Bed', area: 745, beds: 1, baths: 1, rentPsf: 2.20 },
  { key: 'two', name: '2 Bed', area: 1065, beds: 2, baths: 2, rentPsf: 1.85 },
  { key: 'three', name: '3 Bed', area: 1310, beds: 3, baths: 2, rentPsf: 1.62 },
];

export const TYPOLOGIES = {
  garden: {
    key: 'garden',
    name: 'Garden Apartments',
    family: 'residential',
    blurb: '3-story walk-up bars with surface parking bays between them.',
    barDepth: 66,
    minBarLength: 120,
    maxBarLength: 260,
    floors: 3,
    floorToFloor: 10,
    stacked: true,
    corridorWidth: 5,
    coreEvery: 140,
    coreWidth: 14,
    buildingSeparation: 25,
    parkingType: 'surface',
    parkingRatio: 1.7,
    grossToNet: 0.86,
    openSpacePerUnit: 220,
    cost: { shellPsf: 168, parkingPerStall: 5200, softPct: 0.22, contingencyPct: 0.05 },
    ops: { opexPerUnit: 5400, vacancy: 0.06, otherIncomePerUnit: 900, capRate: 0.055 },
  },
  wrap: {
    key: 'wrap',
    name: 'Wrap / Texas Donut',
    family: 'residential',
    blurb: '5-story double-loaded ring wrapping a central parking deck.',
    barDepth: 70,
    minBarLength: 90,
    maxBarLength: 420,
    floors: 5,
    floorToFloor: 10.5,
    stacked: true,
    corridorWidth: 5.5,
    coreEvery: 150,
    coreWidth: 20,
    buildingSeparation: 20,
    parkingType: 'structured',
    parkingRatio: 1.45,
    garageLevels: 5,
    garageSetback: 12,
    perimeterDrive: 22,
    grossToNet: 0.83,
    openSpacePerUnit: 120,
    cost: { shellPsf: 205, parkingPerStall: 24000, softPct: 0.24, contingencyPct: 0.05 },
    ops: { opexPerUnit: 6100, vacancy: 0.06, otherIncomePerUnit: 1400, capRate: 0.05 },
  },
  podium: {
    key: 'podium',
    name: 'Podium Mid-Rise',
    family: 'residential',
    blurb: 'Wood-frame levels over a concrete podium that holds the parking.',
    barDepth: 72,
    minBarLength: 90,
    maxBarLength: 400,
    floors: 6,
    podiumLevels: 2,
    floorToFloor: 10.5,
    stacked: true,
    corridorWidth: 5.5,
    coreEvery: 150,
    coreWidth: 20,
    buildingSeparation: 20,
    parkingType: 'podium',
    parkingRatio: 1.1,
    perimeterDrive: 22,
    grossToNet: 0.81,
    openSpacePerUnit: 90,
    cost: { shellPsf: 248, parkingPerStall: 32000, softPct: 0.26, contingencyPct: 0.06 },
    ops: { opexPerUnit: 6800, vacancy: 0.07, otherIncomePerUnit: 1750, capRate: 0.048 },
  },
  townhome: {
    key: 'townhome',
    name: 'Townhomes',
    family: 'residential',
    blurb: 'Attached fee-simple rows served by rear drive aisles.',
    barDepth: 42,
    minBarLength: 80,
    maxBarLength: 180,
    floors: 3,
    floorToFloor: 9.5,
    // Not stacked: one townhome occupies all of its floors.
    stacked: false,
    defaultMix: { studio: 0, one: 5, two: 55, three: 40 },
    corridorWidth: 0,
    coreEvery: 0,
    coreWidth: 0,
    unitWidth: 20,
    alleyDepth: 44, // one row of guest stalls plus the drive
    buildingSeparation: 24,
    parkingType: 'surface',
    parkingRatio: 2.2, // two in the garage plus guest parking
    garageStallsPerUnit: 2,
    grossToNet: 0.70, // ground-floor garage and stair take the rest
    openSpacePerUnit: 300,
    cost: { shellPsf: 158, parkingPerStall: 4200, softPct: 0.19, contingencyPct: 0.05 },
    ops: { opexPerUnit: 4200, vacancy: 0.05, otherIncomePerUnit: 600, capRate: 0.056 },
    forSale: { pricePsf: 285, sellingCostPct: 0.06 },
  },
  industrial: {
    key: 'industrial',
    name: 'Industrial / Warehouse',
    family: 'commercial',
    blurb: 'Rear-load box with a truck court, trailer stalls and auto parking.',
    barDepth: 320,
    minBarLength: 240,
    maxBarLength: 1400,
    floors: 1,
    floorToFloor: 36,
    buildingSeparation: 40,
    truckCourtDepth: 130,
    trailerStall: { w: 12, d: 53 },
    dockDoorEvery: 50,
    officePct: 0.04,
    parkingType: 'surface',
    parkingRatio: 0.6, // stalls per 1,000 SF
    parkingBasis: 'per1000',
    grossToNet: 1.0,
    cost: { shellPsf: 92, parkingPerStall: 4600, softPct: 0.17, contingencyPct: 0.05 },
    ops: { nnnRentPsf: 9.75, vacancy: 0.05, opexRecoveryPct: 0.95, opexPsf: 2.9, capRate: 0.058 },
  },
  retail: {
    key: 'retail',
    name: 'Retail / Neighborhood Center',
    family: 'commercial',
    blurb: 'Shallow-bay strip along the rear with the parking field up front.',
    barDepth: 65,
    minBarLength: 100,
    maxBarLength: 420,
    floors: 1,
    floorToFloor: 18,
    buildingSeparation: 30,
    bayWidth: 25,
    parkingType: 'surface',
    parkingRatio: 4.5, // stalls per 1,000 SF
    parkingBasis: 'per1000',
    padSites: 2,
    padSize: { w: 90, d: 70 },
    grossToNet: 0.93,
    cost: { shellPsf: 175, parkingPerStall: 5400, softPct: 0.2, contingencyPct: 0.05 },
    ops: { nnnRentPsf: 26, vacancy: 0.08, opexRecoveryPct: 0.9, opexPsf: 6.2, capRate: 0.065 },
  },
};

export const TYPOLOGY_LIST = Object.values(TYPOLOGIES);

export const DEFAULT_MIX = { studio: 12, one: 48, two: 32, three: 8 };

export function defaultParams(typologyKey = 'garden') {
  const t = TYPOLOGIES[typologyKey];
  return {
    typology: typologyKey,
    setbacks: { front: 25, side: 15, rear: 20 },
    frontageEdge: 0,
    rotation: 0, // degrees, relative to the auto-chosen building axis
    axisMode: 'frontage', // 'frontage' | 'longest' | 'manual'
    floors: t.floors,
    barDepth: t.barDepth,
    minBarLength: t.minBarLength,
    maxBarLength: t.maxBarLength,
    buildingSeparation: t.buildingSeparation,
    parkingRatio: t.parkingRatio,
    mix: { ...(t.defaultMix || DEFAULT_MIX) },
    maxCoverage: 0.6,
    maxFar: 2.5,
    maxHeight: 75,
    landPrice: 1_250_000,
    cost: { ...t.cost },
    ops: { ...t.ops },
    seed: 1,
  };
}
